### ISSUE TITLE
Remove stRING and add 1 day min staking period

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/DIP-7#11]
1. Remove stRING and directly call Gov to mint gRING
2. Add requirements of minimum staking period, can unstake after that, just in case staker only stake when collator elect

**Comment by xiaoch05** [comment]
Can we apply a weight to each nominator's vote, with the weight calculated using the formula 
`(sessionEndTime - max(sessionStartTime, StakingTime)) / (sessionEndTime - sessionStartTime)`? 
This method can prevent nominators from using flash loans to rush in at the end of a session and doesn't require imposing a lock-up period.
